version: '3'

services:
  app:
    build: .
    volumes: 
      - ".:/usr/src/app"
      - "./src:/usr/src/app/src"
    ports:
      - "1337:1337"
    env_file: .env
    command: yarn dev

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}