#!/usr/bin/env bash
alias yarn="docker-compose exec app yarn"
alias npm="docker-compose exec app npm"
alias logs="docker-compose logs -f app"
alias sequelize="yarn sequelize"
alias db="sequelize"

alias build="./operations/build.sh"
alias deploy="./operations/deploy.sh"