FROM node:8-alpine

RUN apk --update add git \
  build-base \
  python \
  && mkdir -p /usr/src/app \
  && addgroup -S app && adduser -S -g app app

WORKDIR /usr/src/app

COPY package.json yarn.lock .sequelizerc /usr/src/app/
COPY db /usr/src/app/db
RUN yarn

COPY src/ /usr/src/app/src
RUN chown -R app:app .

EXPOSE 1337

CMD yarn start